application: mythic-code-689
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /login
  script: FirstWords.application

- url: /api/.*
  script: FirstWords.application

- url: /tasks/.*
  script: FirstWords.application

- url: /.*
  script: FirstWords.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest
